name: Update README with Joke

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script to update README
      run: node index.js # Replace with your actual script file

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.name 'Jayesh1512'
        git config --global user.email 'jayeshshetestudy@gmail.com'
        git add README.md
        git commit -m "New Joke added"
        git push https://<your-username>:${{ secrets.ACTIONS_PAT }}@github.com/<your-username>/<your-repository>.git
